/**
 * Seed script: Narasimha Restaurants (Hungry Island) — full menu
 * Run: npx tsx scripts/seed-narasimha-menu.ts
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const TENANT_ID = 'cmrrm96yf0009qp64zxg3cpia';

// ── Online image URLs (Unsplash / free sources) ──
const IMG: Record<string, string> = {
  soups: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
  vegStarters: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400',
  nonVegStarters: 'https://images.unsplash.com/photo-1610057099960-f442db4847a5?w=400',
  seafood: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400',
  vegCurries: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
  nonVegCurries: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
  tandoori: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
  friedRice: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
  roti: 'https://images.unsplash.com/photo-1565557623262-b513d5e5fd47?w=400',
  vegBiryani: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
  nonVegBiryani: 'https://images.unsplash.com/photo-1589302168068-964664d9f601?w=400',
  specialBiryani: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
  familyPack: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
  shawarma: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400',
  mandi: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
  mocktails: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400',
  iceCream: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400',
  softDrinks: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?w=400',
  // specific item images
  hotNSour: 'https://images.unsplash.com/photo-1607330289024-1535c6b4e1c1?w=400',
  cornSoup: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
  manchowSoup: 'https://images.unsplash.com/photo-1583032015879-e5022cb87c3b?w=400',
  clearSoup: 'https://images.unsplash.com/photo-1607330289024-1535c6b4e1c1?w=400',
  manchuria: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400',
  gobi: 'https://images.unsplash.com/photo-1610057099960-f442db4847a5?w=400',
  mushroom: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
  paneer65: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
  babycorn: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400',
  egg: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400',
  chilliChicken: 'https://images.unsplash.com/photo-1610057099960-f442db4847a5?w=400',
  chicken65: 'https://images.unsplash.com/photo-1610057099960-f442db4847a5?w=400',
  dragon: 'https://images.unsplash.com/photo-1610057099960-f442db4847a5?w=400',
  lollipop: 'https://images.unsplash.com/photo-1610057099960-f442db4847a5?w=400',
  apolloFish: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400',
  fish65: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400',
  prawns: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400',
  butterChicken: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
  muttonCurry: 'https://images.unsplash.com/photo-1565557623262-b513d5e5fd41?w=400',
  chickenTikka: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
  grillChicken: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
  friedRice: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
  noodles: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400',
  naan: 'https://images.unsplash.com/photo-1565557623262-b513d5e5fd47?w=400',
  biryani: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
  dumBiryani: 'https://images.unsplash.com/photo-1589302168068-964664d9f601?w=400',
  muttonBiryani: 'https://images.unsplash.com/photo-1589302168068-964664d9f601?w=400',
  paneerBiryani: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
  family: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
  shawarmaImg: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400',
  mandiImg: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
  mojito: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400',
  lassi: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400',
  chocolateShake: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400',
  vanillaIce: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400',
  sundae: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400',
};

type ItemDef = { name: string; price: number; isVeg: boolean; tags?: string[]; image?: string; popular?: boolean; bestSeller?: boolean; chefRec?: boolean };

const MENU: { category: string; sortOrder: number; image: string; items: ItemDef[] }[] = [
  {
    category: 'Soups',
    sortOrder: 0,
    image: IMG.soups,
    items: [
      { name: 'Veg Hot N Sour', price: 99, isVeg: true, image: IMG.hotNSour },
      { name: 'Veg Corn Soup', price: 119, isVeg: true, image: IMG.cornSoup },
      { name: 'Veg Manchow Soup', price: 119, isVeg: true, image: IMG.manchowSoup },
      { name: 'Veg Clear Soup', price: 129, isVeg: true, image: IMG.clearSoup },
      { name: 'Chicken Hot N Sour', price: 129, isVeg: false, image: IMG.hotNSour },
      { name: 'Chicken Corn Soup', price: 129, isVeg: false, image: IMG.cornSoup },
      { name: 'Chicken Manchow', price: 139, isVeg: false, image: IMG.manchowSoup },
      { name: 'Chicken Clear Soup', price: 139, isVeg: false, image: IMG.clearSoup },
      { name: 'Mutton Bone Soup', price: 160, isVeg: false, image: IMG.clearSoup },
      { name: 'Mutton Boneless Soup', price: 180, isVeg: false, image: IMG.clearSoup, popular: true },
    ],
  },
  {
    category: 'Veg Starters',
    sortOrder: 1,
    image: IMG.vegStarters,
    items: [
      { name: 'Veg Manchuria', price: 130, isVeg: true, image: IMG.manchuria },
      { name: 'Gobi Manchuria', price: 130, isVeg: true, image: IMG.gobi, popular: true },
      { name: 'Special Veg Manchuria', price: 150, isVeg: true, image: IMG.manchuria },
      { name: 'Mushroom 65', price: 180, isVeg: true, image: IMG.mushroom },
      { name: 'Chilli Mushroom', price: 180, isVeg: true, image: IMG.mushroom },
      { name: 'Mushroom Manchuria', price: 180, isVeg: true, image: IMG.mushroom },
      { name: 'Paneer Manchuria', price: 210, isVeg: true, image: IMG.paneer65 },
      { name: 'Baby Corn Majestic', price: 220, isVeg: true, image: IMG.babycorn },
      { name: 'Baby Corn 65', price: 220, isVeg: true, image: IMG.babycorn },
      { name: 'Paneer Majestic', price: 260, isVeg: true, image: IMG.paneer65, bestSeller: true },
    ],
  },
  {
    category: 'Non-Veg Starters',
    sortOrder: 2,
    image: IMG.nonVegStarters,
    items: [
      { name: 'Egg Burji', price: 130, isVeg: false, image: IMG.egg },
      { name: 'Egg Manchuria', price: 190, isVeg: false, image: IMG.egg },
      { name: 'Chicken Manchuria', price: 219, isVeg: false, image: IMG.chilliChicken },
      { name: 'Chicken Roast', price: 240, isVeg: false, image: IMG.chilliChicken },
      { name: 'Chilli Chicken', price: 249, isVeg: false, image: IMG.chilliChicken, popular: true, bestSeller: true },
      { name: 'Chicken 65', price: 280, isVeg: false, image: IMG.chicken65, popular: true, bestSeller: true },
      { name: 'Chicken 555', price: 280, isVeg: false, image: IMG.chilliChicken },
      { name: 'Dragon Chicken', price: 280, isVeg: false, image: IMG.dragon },
      { name: 'Hawai Chicken', price: 290, isVeg: false, image: IMG.chilliChicken },
      { name: 'Chicken Majestic', price: 290, isVeg: false, image: IMG.chilliChicken, bestSeller: true },
      { name: 'Lemon Chicken', price: 290, isVeg: false, image: IMG.chilliChicken },
      { name: 'Honey Chicken', price: 320, isVeg: false, image: IMG.chilliChicken },
      { name: 'Chicken Lollipop (5 pcs)', price: 320, isVeg: false, image: IMG.lollipop, popular: true },
      { name: 'Special Baby Wings (12 pcs)', price: 320, isVeg: false, image: IMG.chicken65 },
      { name: 'Red Bull Chicken', price: 340, isVeg: false, image: IMG.chilliChicken },
      { name: 'Chicken Mangolia', price: 340, isVeg: false, image: IMG.chilliChicken },
      { name: 'Mutton 85', price: 340, isVeg: false, image: IMG.muttonCurry },
      { name: 'Chicken Gurjala', price: 349, isVeg: false, image: IMG.chilliChicken },
      { name: 'Karivepaku Kodi', price: 350, isVeg: false, image: IMG.chilliChicken },
      { name: 'Pepper Chicken', price: 359, isVeg: false, image: IMG.chilliChicken },
      { name: 'RR Chicken', price: 360, isVeg: false, image: IMG.chilliChicken },
    ],
  },
  {
    category: 'Seafood Starters',
    sortOrder: 3,
    image: IMG.seafood,
    items: [
      { name: 'Apollo Fish', price: 299, isVeg: false, image: IMG.apolloFish, popular: true, bestSeller: true },
      { name: 'Fish 65', price: 299, isVeg: false, image: IMG.fish65 },
      { name: 'Chilli Fish', price: 310, isVeg: false, image: IMG.fish65 },
      { name: 'Fish Roast', price: 310, isVeg: false, image: IMG.fish65 },
      { name: 'Pepper Fish', price: 320, isVeg: false, image: IMG.fish65 },
      { name: 'Fried Fish', price: 330, isVeg: false, image: IMG.fish65 },
      { name: 'Pepper Prawns', price: 310, isVeg: false, image: IMG.prawns },
      { name: 'Dragon Prawns', price: 310, isVeg: false, image: IMG.prawns },
      { name: 'Loose Prawns', price: 320, isVeg: false, image: IMG.prawns },
      { name: 'Chilli Prawns', price: 320, isVeg: false, image: IMG.prawns },
      { name: 'Golden Fried Prawns', price: 330, isVeg: false, image: IMG.prawns, bestSeller: true },
    ],
  },
  {
    category: 'Veg Curries',
    sortOrder: 4,
    image: IMG.vegCurries,
    items: [
      { name: 'Veg Mixed Curry', price: 120, isVeg: true, image: IMG.vegCurries },
      { name: 'Paneer Butter Masala', price: 200, isVeg: true, image: IMG.paneer65, popular: true, bestSeller: true },
      { name: 'Mushroom Curry', price: 200, isVeg: true, image: IMG.mushroom },
      { name: 'Kaju Curry', price: 240, isVeg: true, image: IMG.vegCurries },
      { name: 'Methi Chaman Curry', price: 200, isVeg: true, image: IMG.vegCurries },
      { name: 'Palak Chaman Paneer', price: 200, isVeg: true, image: IMG.paneer65 },
      { name: 'Kaju Tomato Curry', price: 260, isVeg: true, image: IMG.vegCurries },
      { name: 'Kaju Paneer Curry', price: 270, isVeg: true, image: IMG.paneer65 },
    ],
  },
  {
    category: 'Non-Veg Curries',
    sortOrder: 5,
    image: IMG.nonVegCurries,
    items: [
      { name: 'Egg Curry', price: 160, isVeg: false, image: IMG.egg },
      { name: 'Chicken Bone Curry', price: 200, isVeg: false, image: IMG.nonVegCurries },
      { name: 'Chicken Boneless Curry', price: 220, isVeg: false, image: IMG.nonVegCurries },
      { name: 'Butter Chicken', price: 250, isVeg: false, image: IMG.butterChicken, popular: true, bestSeller: true },
      { name: 'Andhra Chicken', price: 250, isVeg: false, image: IMG.nonVegCurries },
      { name: 'Kadai Chicken', price: 260, isVeg: false, image: IMG.nonVegCurries },
      { name: 'Mogalai Chicken', price: 260, isVeg: false, image: IMG.nonVegCurries },
      { name: 'Mutton Curry', price: 330, isVeg: false, image: IMG.muttonCurry },
      { name: 'Mutton Fry', price: 310, isVeg: false, image: IMG.muttonCurry },
      { name: 'Prawns Curry', price: 290, isVeg: false, image: IMG.prawns },
      { name: 'Andhra Mutton', price: 330, isVeg: false, image: IMG.muttonCurry },
      { name: 'Gongura Mutton', price: 330, isVeg: false, image: IMG.muttonCurry, popular: true },
      { name: 'Chicken Maharani', price: 310, isVeg: false, image: IMG.nonVegCurries },
      { name: 'Mutton Maharani', price: 390, isVeg: false, image: IMG.muttonCurry },
      { name: 'Gongura Prawns', price: 310, isVeg: false, image: IMG.prawns },
      { name: 'Kadai Mutton', price: 340, isVeg: false, image: IMG.muttonCurry },
    ],
  },
  {
    category: 'Tandoori',
    sortOrder: 6,
    image: IMG.tandoori,
    items: [
      { name: 'Tandoori Full (8 pcs)', price: 550, isVeg: false, image: IMG.tandoori, popular: true, bestSeller: true },
      { name: 'Tandoori Half (4 pcs)', price: 280, isVeg: false, image: IMG.tandoori },
      { name: 'Chicken Tikka (8 pcs)', price: 300, isVeg: false, image: IMG.chickenTikka, popular: true },
      { name: 'Tangdi Kebab Full (4 pcs)', price: 360, isVeg: false, image: IMG.tandoori },
      { name: 'Tangdi Kebab Half (2 pcs)', price: 180, isVeg: false, image: IMG.tandoori },
      { name: 'Hariyali Kebab', price: 280, isVeg: false, image: IMG.tandoori },
      { name: 'Paneer Tikka', price: 280, isVeg: true, image: IMG.paneer65, popular: true },
      { name: 'Grill Chicken Full', price: 490, isVeg: false, image: IMG.grillChicken, bestSeller: true },
      { name: 'Grill Chicken Half', price: 280, isVeg: false, image: IMG.grillChicken },
    ],
  },
  {
    category: 'Fried Rice & Noodles',
    sortOrder: 7,
    image: IMG.friedRice,
    items: [
      { name: 'Jeera Rice', price: 160, isVeg: true, image: IMG.friedRice },
      { name: 'Veg Fried Rice', price: 160, isVeg: true, image: IMG.friedRice, popular: true },
      { name: 'Egg Fried Rice', price: 170, isVeg: false, image: IMG.friedRice },
      { name: 'Ghee Fried Rice', price: 190, isVeg: true, image: IMG.friedRice },
      { name: 'Chicken Fried Rice', price: 220, isVeg: false, image: IMG.friedRice, popular: true, bestSeller: true },
      { name: 'Paneer Fried Rice', price: 220, isVeg: true, image: IMG.friedRice },
      { name: 'Paneer Special Fried Rice', price: 270, isVeg: true, image: IMG.friedRice },
      { name: 'Mushroom Fried Rice', price: 230, isVeg: true, image: IMG.friedRice },
      { name: 'Chicken Noodles', price: 220, isVeg: false, image: IMG.noodles, popular: true },
      { name: 'Egg Noodles', price: 180, isVeg: false, image: IMG.noodles },
      { name: 'Veg Noodles', price: 150, isVeg: true, image: IMG.noodles },
      { name: 'Kaju Fried Rice', price: 230, isVeg: true, image: IMG.friedRice },
      { name: 'Kaju Special Fried Rice', price: 260, isVeg: true, image: IMG.friedRice },
      { name: 'Special Chicken Fried Rice', price: 270, isVeg: false, image: IMG.friedRice },
      { name: 'Mixed Non-Veg Fried Rice', price: 350, isVeg: false, image: IMG.friedRice },
      { name: 'Mutton Fried Rice', price: 370, isVeg: false, image: IMG.friedRice },
      { name: 'Prawns Fried Rice', price: 360, isVeg: false, image: IMG.friedRice },
      { name: 'Curd Rice', price: 90, isVeg: true, image: IMG.friedRice },
      { name: 'Special Curd Rice', price: 120, isVeg: true, image: IMG.friedRice },
      { name: 'Steam Rice', price: 140, isVeg: true, image: IMG.friedRice },
    ],
  },
  {
    category: 'Rotis & Naans',
    sortOrder: 8,
    image: IMG.roti,
    items: [
      { name: 'Pulka', price: 15, isVeg: true, image: IMG.naan },
      { name: 'Tandoori Roti', price: 35, isVeg: true, image: IMG.naan },
      { name: 'Butter Roti', price: 40, isVeg: true, image: IMG.naan },
      { name: 'Garlic Roti', price: 45, isVeg: true, image: IMG.naan },
      { name: 'Butter Naan', price: 45, isVeg: true, image: IMG.naan, popular: true },
      { name: 'Garlic Naan', price: 50, isVeg: true, image: IMG.naan },
      { name: 'Aloo Kulcha', price: 80, isVeg: true, image: IMG.naan },
      { name: 'Paneer Kulcha', price: 100, isVeg: true, image: IMG.naan },
      { name: 'Masala Kulcha', price: 100, isVeg: true, image: IMG.naan },
      { name: 'Chicken Kulcha', price: 120, isVeg: false, image: IMG.naan },
    ],
  },
  {
    category: 'Veg Biryani',
    sortOrder: 9,
    image: IMG.vegBiryani,
    items: [
      { name: 'Veg Biryani', price: 189, isVeg: true, image: IMG.vegBiryani, popular: true, bestSeller: true },
      { name: 'Gongura Biryani', price: 189, isVeg: true, image: IMG.vegBiryani },
      { name: 'Egg Biryani', price: 240, isVeg: false, image: IMG.biryani, popular: true },
      { name: 'Paneer Biryani', price: 270, isVeg: true, image: IMG.paneerBiryani },
      { name: 'Mushroom Biryani', price: 270, isVeg: true, image: IMG.mushroom },
      { name: 'Kaju Biryani', price: 270, isVeg: true, image: IMG.paneerBiryani },
      { name: 'Kaju Special Biryani', price: 299, isVeg: true, image: IMG.paneerBiryani },
      { name: 'Paneer Kaju Biryani', price: 320, isVeg: true, image: IMG.paneerBiryani },
    ],
  },
  {
    category: 'Non-Veg Biryani',
    sortOrder: 10,
    image: IMG.nonVegBiryani,
    items: [
      { name: 'Mini Dum Biryani', price: 160, isVeg: false, image: IMG.biryani },
      { name: 'Dum Biryani', price: 260, isVeg: false, image: IMG.dumBiryani, popular: true, bestSeller: true },
      { name: 'Mini Fry Piece Biryani', price: 170, isVeg: false, image: IMG.biryani },
      { name: 'Fry Piece Biryani', price: 270, isVeg: false, image: IMG.dumBiryani, popular: true },
      { name: 'Hungry Island Special Biryani (Bone)', price: 280, isVeg: false, image: IMG.dumBiryani, bestSeller: true, chefRec: true },
      { name: 'Hungry Island Special Biryani (Boneless)', price: 300, isVeg: false, image: IMG.dumBiryani, popular: true, chefRec: true },
      { name: 'Joint Biryani', price: 269, isVeg: false, image: IMG.biryani },
      { name: 'Kothimeera Biryani', price: 269, isVeg: false, image: IMG.biryani },
      { name: 'Mogalai Biryani', price: 289, isVeg: false, image: IMG.dumBiryani },
      { name: 'Gongura Biryani', price: 290, isVeg: false, image: IMG.biryani },
      { name: 'Lollipop Biryani', price: 300, isVeg: false, image: IMG.biryani },
      { name: 'Wings Biryani', price: 300, isVeg: false, image: IMG.biryani },
      { name: 'Tikka Biryani', price: 320, isVeg: false, image: IMG.biryani },
      { name: 'Kings Biryani', price: 339, isVeg: false, image: IMG.dumBiryani },
      { name: 'Fish Juicy Biryani', price: 340, isVeg: false, image: IMG.biryani },
      { name: 'Prawns Biryani', price: 349, isVeg: false, image: IMG.biryani },
      { name: 'Gongura Prawns Biryani', price: 349, isVeg: false, image: IMG.biryani },
      { name: 'Gongura Mutton Biryani', price: 369, isVeg: false, image: IMG.muttonBiryani },
      { name: 'Mutton Biryani', price: 379, isVeg: false, image: IMG.muttonBiryani, popular: true },
      { name: 'Rambo Biryani', price: 389, isVeg: false, image: IMG.dumBiryani },
    ],
  },
  {
    category: 'Special Biryanis',
    sortOrder: 11,
    image: IMG.specialBiryani,
    items: [
      { name: 'Afgani Biryani', price: 310, isVeg: false, image: IMG.biryani },
      { name: 'Dilkush Biryani', price: 320, isVeg: false, image: IMG.biryani },
      { name: 'Tangdi Biryani', price: 320, isVeg: false, image: IMG.biryani },
      { name: 'Chicken Maharaja Biryani', price: 340, isVeg: false, image: IMG.dumBiryani, popular: true },
      { name: 'Punjabi Chicken Biryani', price: 350, isVeg: false, image: IMG.biryani },
      { name: 'Andhra Mutton Biryani', price: 390, isVeg: false, image: IMG.muttonBiryani, popular: true },
      { name: 'Mutton Kheema Biryani', price: 399, isVeg: false, image: IMG.muttonBiryani },
      { name: 'Mixed Non-Veg Biryani', price: 399, isVeg: false, image: IMG.dumBiryani },
      { name: 'Mutton Maharaja Biryani', price: 420, isVeg: false, image: IMG.muttonBiryani, bestSeller: true, chefRec: true },
    ],
  },
  {
    category: 'Family Packs',
    sortOrder: 12,
    image: IMG.familyPack,
    items: [
      { name: 'Veg Family Pack', price: 549, isVeg: true, image: IMG.family },
      { name: 'Paneer Family Pack', price: 549, isVeg: true, image: IMG.family },
      { name: 'Mushroom Family Pack', price: 549, isVeg: true, image: IMG.family },
      { name: 'Chicken Dum Family Pack', price: 650, isVeg: false, image: IMG.family, popular: true, bestSeller: true },
      { name: 'Chicken Fry Family Pack', price: 650, isVeg: false, image: IMG.family },
      { name: 'Chicken Wing Family Pack', price: 650, isVeg: false, image: IMG.family },
      { name: 'Chicken Lollipop Family Pack', price: 650, isVeg: false, image: IMG.family },
      { name: 'Mutton Fry Family Pack', price: 900, isVeg: false, image: IMG.family },
      { name: 'Kumbakarna Family Pack', price: 890, isVeg: false, image: IMG.family, chefRec: true },
    ],
  },
  {
    category: 'Shawarma',
    sortOrder: 13,
    image: IMG.shawarma,
    items: [
      { name: 'Regular Shawarma', price: 120, isVeg: false, image: IMG.shawarmaImg, popular: true },
      { name: 'Special Shawarma', price: 140, isVeg: false, image: IMG.shawarmaImg, bestSeller: true },
      { name: 'Spicy Chicken Shawarma', price: 140, isVeg: false, image: IMG.shawarmaImg },
      { name: 'Schezwan Shawarma', price: 140, isVeg: false, image: IMG.shawarmaImg },
      { name: 'Mint Mayo Shawarma', price: 140, isVeg: false, image: IMG.shawarmaImg },
      { name: 'Sweet Chilli Shawarma', price: 140, isVeg: false, image: IMG.shawarmaImg },
      { name: 'Chicken Peri Peri Shawarma', price: 140, isVeg: false, image: IMG.shawarmaImg },
      { name: 'Cheese & Spice Shawarma', price: 160, isVeg: false, image: IMG.shawarmaImg },
      { name: 'Special Chicken Plate Shawarma', price: 169, isVeg: false, image: IMG.shawarmaImg },
      { name: 'Fully Loaded Chicken Shawarma', price: 180, isVeg: false, image: IMG.shawarmaImg },
      { name: 'Special Kaju Shawarma', price: 180, isVeg: false, image: IMG.shawarmaImg },
      { name: 'Chilli Chicken Shawarma', price: 220, isVeg: false, image: IMG.shawarmaImg },
    ],
  },
  {
    category: 'Mandi',
    sortOrder: 14,
    image: IMG.mandi,
    items: [
      { name: 'Tandoori Mandi Full', price: 880, isVeg: false, image: IMG.mandiImg, popular: true },
      { name: 'Tandoori Mandi Half', price: 490, isVeg: false, image: IMG.mandiImg },
      { name: 'Juicy Mandi Full', price: 880, isVeg: false, image: IMG.mandiImg },
      { name: 'Juicy Mandi Half', price: 490, isVeg: false, image: IMG.mandiImg },
      { name: 'Afgani Mandi Full', price: 999, isVeg: false, image: IMG.mandiImg },
      { name: 'Afgani Mandi Half', price: 560, isVeg: false, image: IMG.mandiImg },
      { name: 'Lollipop Mandi Full', price: 1120, isVeg: false, image: IMG.mandiImg },
      { name: 'Lollipop Mandi Half', price: 600, isVeg: false, image: IMG.mandiImg },
      { name: 'Prawns Juicy Mandi Full', price: 1200, isVeg: false, image: IMG.mandiImg },
      { name: 'Prawns Juicy Mandi Half', price: 650, isVeg: false, image: IMG.mandiImg },
      { name: 'Mutton Juicy Mandi Full', price: 1300, isVeg: false, image: IMG.mandiImg, popular: true },
      { name: 'Mutton Juicy Mandi Half', price: 700, isVeg: false, image: IMG.mandiImg },
      { name: 'Fish Juicy Mandi Full', price: 1200, isVeg: false, image: IMG.mandiImg },
      { name: 'Fish Juicy Mandi Half', price: 650, isVeg: false, image: IMG.mandiImg },
      { name: 'Mixed Non-Veg Mandi Full', price: 1200, isVeg: false, image: IMG.mandiImg, bestSeller: true },
      { name: 'Mixed Non-Veg Mandi Half', price: 700, isVeg: false, image: IMG.mandiImg },
      { name: 'Special Ghatotkacha Mandi', price: 1500, isVeg: false, image: IMG.mandiImg, chefRec: true },
      { name: 'Paneer Mandi Full', price: 1000, isVeg: true, image: IMG.mandiImg },
      { name: 'Paneer Mandi Half', price: 550, isVeg: true, image: IMG.mandiImg },
    ],
  },
  {
    category: 'Mocktails & Drinks',
    sortOrder: 15,
    image: IMG.mocktails,
    items: [
      { name: 'Topical Fizz', price: 120, isVeg: true, image: IMG.mojito },
      { name: 'Guava Salsa', price: 120, isVeg: true, image: IMG.mojito },
      { name: 'Virgin Mojito', price: 90, isVeg: true, image: IMG.mojito, popular: true },
      { name: 'Blue Lagoon', price: 90, isVeg: true, image: IMG.mojito },
      { name: 'Lemon Ginger', price: 90, isVeg: true, image: IMG.mojito },
      { name: 'Orange Blast', price: 90, isVeg: true, image: IMG.mojito },
      { name: 'Honey Lemon', price: 90, isVeg: true, image: IMG.mojito },
      { name: 'Mango Crush', price: 90, isVeg: true, image: IMG.mojito },
      { name: 'Strawberry Crush', price: 90, isVeg: true, image: IMG.mojito },
      { name: 'Mango Lassi', price: 100, isVeg: true, image: IMG.lassi, popular: true },
      { name: 'Rose Lassi', price: 100, isVeg: true, image: IMG.lassi },
      { name: 'Buttermilk', price: 40, isVeg: true, image: IMG.lassi },
      { name: 'Sweet Soda', price: 40, isVeg: true, image: IMG.mocktails },
      { name: 'Salt Soda', price: 40, isVeg: true, image: IMG.mocktails },
      { name: 'Chocolate Milk Shake', price: 120, isVeg: true, image: IMG.chocolateShake },
      { name: 'Strawberry Shake', price: 120, isVeg: true, image: IMG.chocolateShake },
      { name: 'Rose Milk Shake', price: 120, isVeg: true, image: IMG.chocolateShake },
      { name: 'Lassi', price: 60, isVeg: true, image: IMG.lassi },
    ],
  },
  {
    category: 'Ice Creams',
    sortOrder: 16,
    image: IMG.iceCream,
    items: [
      { name: 'Vanilla', price: 75, isVeg: true, image: IMG.vanillaIce },
      { name: 'Strawberry', price: 75, isVeg: true, image: IMG.vanillaIce },
      { name: 'Pista', price: 85, isVeg: true, image: IMG.vanillaIce },
      { name: 'Butter Scotch', price: 95, isVeg: true, image: IMG.vanillaIce },
      { name: 'Chocolate', price: 95, isVeg: true, image: IMG.vanillaIce },
      { name: 'Ultimate Sundae', price: 130, isVeg: true, image: IMG.sundae, popular: true, bestSeller: true },
    ],
  },
  {
    category: 'Soft Drinks',
    sortOrder: 17,
    image: IMG.softDrinks,
    items: [
      { name: 'Thums Up 250ml (MRP)', price: 20, isVeg: true, image: IMG.softDrinks },
      { name: 'Sprite 250ml (MRP)', price: 20, isVeg: true, image: IMG.softDrinks },
      { name: 'Coca-Cola 250ml (MRP)', price: 20, isVeg: true, image: IMG.softDrinks },
      { name: 'Water Bottle 500ml (MRP)', price: 20, isVeg: true, image: IMG.softDrinks },
    ],
  },
];

async function main() {
  console.log('🍽️  Seeding Narasimha Restaurants menu...');

  // Delete existing menu items and categories
  console.log('  Cleaning old menu items...');
  await prisma.$executeRaw`DELETE FROM menu_items WHERE "tenantId" = ${TENANT_ID}`;
  console.log('  Cleaning old categories...');
  await prisma.$executeRaw`DELETE FROM categories WHERE "tenantId" = ${TENANT_ID}`;

  let totalItems = 0;

  for (const cat of MENU) {
    const category = await prisma.category.create({
      data: {
        tenantId: TENANT_ID,
        name: cat.category,
        sortOrder: cat.sortOrder,
        image: cat.image,
        isActive: true,
      },
    });

    for (const item of cat.items) {
      await prisma.menuItem.create({
        data: {
          tenantId: TENANT_ID,
          categoryId: category.id,
          name: item.name,
          price: item.price,
          isVeg: item.isVeg,
          isAvailable: true,
          isPopular: item.popular || false,
          isBestSeller: item.bestSeller || false,
          isChefRecommendation: item.chefRec || false,
          image: item.image,
          tags: item.tags || [],
          taxRate: 5,
        },
      });
      totalItems++;
    }

    console.log(`  ✅ ${cat.category}: ${cat.items.length} items`);
  }

  console.log(`\n🎉 Seeded ${MENU.length} categories with ${totalItems} menu items`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
